primary_region = "ams"

[build]
  dockerfile = "../Dockerfile.tasks"

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 80
  force_https = true

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"
