import type { NextPage } from 'next'
import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import { ContactForm } from '../components/ContactForm'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <ContactForm></ContactForm>
    </>
  )
}

export default Home
