import type { NextPage } from 'next'
import Head from 'next/head'
import { Navbar } from '../components/Navbar'

const Home: NextPage = () => {
  return (
      <div>
        <Head>
          <title>helpwave</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar></Navbar>
      </div>
  )
}

export default Home
