import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
      <div>
        <Head>
          <title>helpwave</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="text-3xl font-bold underline">
          helpwave is cool
        </h1>
      </div>
  )
}

export default Home
