import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth } from '../hooks/useAuth'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  const { user, logout, accessToken } = useAuth(() => router.push({ pathname: '/login', query: { back: true } }))

  console.log(user, accessToken)

  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="text-3xl font-bold underline">
          {user === null ? 'Redirecting to log in page..' : `Hello ${user.username}`}
        </h1>

        <button onClick={() => logout(() => window.location.reload())}>Logout</button>
      </div>
  )
}

export default Home
