import Cookies from 'js-cookie'
import type { NextPage } from 'next'
import Head from 'next/head'
import useAuth from '../hooks/useAuth'
import { loginWithCredentials } from '../utils/login'

const loginProcessMock = () => {
  console.log('logging in..')
  return loginWithCredentials({ username: '', password: '' })
    .then(accessToken => Cookies.set('jwt-access-token', accessToken))
}

const Home: NextPage = () => {
  const { user, logout, accessToken } = useAuth(loginProcessMock)

  console.log(user, accessToken)

  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="text-3xl font-bold underline">
          {user === null ? 'Logging in..' : `Hello ${user.username}`}
        </h1>

        <button onClick={() => logout(() => window.location.reload())}>Logout</button>
      </div>
  )
}

export default Home
