import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Cookies from 'js-cookie'
import { loginWithCredentials } from '../utils/login'
import { Input } from '../components/Input'
import { Checkbox } from '../components/Checkbox'

import HelpwaveLogo from '../icons/Helpwave'

// TODO: localization
const LoginPage: NextPage = () => {
  const router = useRouter()
  const [rememberMe, setRememberMe] = useState(false)
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')

  const handleLogin = () => {
    // TODO: input validation?
    loginWithCredentials({ username: '', password: '', shouldRetrieveRefreshToken: rememberMe })
      .then(accessToken => {
        Cookies.set('jwt-access-token', accessToken)

        if (router.query.back) {
          router.back()
        } else {
          router.push('/')
        }
      })
      .catch(err => {
        // TODO: somehow display error messages
      })
  }

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center py-12 px-4">
        <div className="w-full max-w-md space-y-8">
          <div>
            <HelpwaveLogo className="mx-auto h-12 w-auto" />
            <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign in to your organization</h2>
            <p className="mt-4 text-center text-sm text-gray-600">
                Or{' '}
                <Link href="/contact" passHref>
                  <a className="font-medium text-indigo-600 hover:text-indigo-500">
                    contact us
                  </a>
                </Link>
                {' '}for access.
              </p>
            </div>
          <div className="flex flex-col mt-8 space-y-4 items-center">
            <div className="w-80">
              <Input id="login:username" autocomplete="username" placeholder="Username" label="Username" value={username} onChange={setUsername} />
            </div>
            <div className="w-80">
              <Input id="login:password" autocomplete="current-password" placeholder="Password" label="Password" value={password} onChange={setPassword} />
            </div>

            <div className="flex items-center justify-between w-80">
              <Checkbox id="login:remember-me" label="Remember me" onChange={setRememberMe} checked={rememberMe} />
              <div className="text-sm">
                <Link href="/forgot-password" passHref>
                  <a className="font-medium text-indigo-600 hover:text-indigo-500">Forgot your password?</a>
                </Link>
              </div>
            </div>

            <div className="w-80">
              <button onClick={handleLogin} className="bg-indigo-600 py-2 px-4 text-sm font-medium text-white rounded-md w-full hover:bg-indigo-700 focus:outline-none focus:ring-indigo-500 focus:ring-2 focus:ring-offset-2">
                Sign in
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default LoginPage
