import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import cx from 'classnames'
import { useAuth } from '../hooks/useAuth'
import { useRouter } from 'next/router'
import { Header } from '../components/Header'
import { UserMenu } from '../components/UserMenu'
import { Button } from '../components/Button'
import { Input, noop } from '../components/Input'
import { ProfilePicture } from '../components/ProfilePicture'
import { UserCard } from '../components/UserCard'

const ProfilePage: NextPage = () => {
  const router = useRouter()
  const { user, logout, accessToken } = useAuth(() => router.push({ pathname: '/login', query: { back: true } }))

  const [fullName, setFullName] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [avatarUrl, setAvatarUrl] = useState('')

  useEffect(() => {
    if (user) {
      setFullName(user.fullName)
      setDisplayName(user.displayName)
      setAvatarUrl(user.avatarUrl)
    }
  }, [user])

  const save = () => {
    console.log('saving the following changes', {
      fullName,
      displayName
    })
  }

  if (!user) return null

  return (
    <div className="w-screen h-screen flex flex-col">
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="helpwave" navigation={[
        { text: 'Dashboard', href: '/' },
        { text: 'Contact', href: '/contact' },
      ]} actions={[
        <UserMenu key="user-menu" user={user} />
      ]} />

      <div className="p-4 w-full h-full">
        <h1 className="text-xl text-slate-700 font-medium pb-2">Profile</h1>

        <span>This is how you appear to others</span>

        <div className="p-2">
          <UserCard user={{ ...user, fullName, displayName, avatarUrl }} />
        </div>

        <br />

        <div>
          <span>Update your avatar</span>

          <div className="w-64 p-4">

          <ProfilePicture avatarUrl={avatarUrl} altText="profile picture" size="large" />
          {/* For now this is just a text input for a url, this should become some kind of file chooser in the future */}
          <Input id="profile:avatar-url" label="Avatar URL" value={avatarUrl} onChange={setAvatarUrl} />
        </div>
        </div>

        <br />

        <div>
          <span>Update your full name and display name</span>

          <div className="w-64 p-4">
            <Input id="profile:fullname" label="Full name" value={fullName} onChange={setFullName} />
            <br />
            <Input id="profile:displayname" label="Display name" value={displayName} onChange={setDisplayName} />
            <br />
            <Input id="profile:email" label="Email" value={user.email} onChange={noop} disabled />
          </div>

        </div>

        <Button variant="primary" onClick={save}>Save</Button>

        <br />
        <br />

        <div>
          <span>You are part of the following organizations</span>

          <div className="w-80 p-4">
            {user.organizations.map(organization => (
              <div key={organization.id} className="flex items-center gap-2">
                {organization.shortName} ({organization.longName})
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default ProfilePage
