export const textStyles: [string, string][] = [
  ['textstyle-title-3xl', 'text-5xl font-space font-bold'],
  ['textstyle-title-2xl', 'text-4xl font-space font-bold'],
  ['textstyle-title-xl', 'text-3xl font-space font-bold'],
  ['textstyle-title-lg', 'text-2xl font-space font-bold'],
  ['textstyle-title-md', 'text-xl font-space font-bold'],
  ['textstyle-title-normal', 'text-lg font-semibold'],
  ['textstyle-title-sm', 'font-space font-bold'],
  ['textstyle-accent', 'text-sm text-gray-600 font-bold'],
  ['textstyle-description', 'text-gray-400'],
  ['textstyle-label-lg', 'text-lg font-semibold'],
  ['textstyle-label-md', 'text-gray-700 font-semibold'],
  ['textstyle-label-sm', 'text-sm text-gray-700 font-semibold'],
  ['textstyle-table-name', 'text-lg font-space font-medium'],
  ['textstyle-table-header', 'text-gray-600 font-bold'],
  ['textstyle-navigation-item', 'font-bold font-space'],
  ['textstyle-form-error', 'text-hw-negative-500 text-sm'],
  ['textstyle-form-description', 'text-gray-500 text-sm'],
]
