name: CI

env:
  NODE_VERSION: 20.4.0
  PNPM_VERSION: 8

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
          scope: "@helpwave"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm cache directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "directory=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.directory }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cache-

      - name: Install pnpm dependencies
        run: pnpm install

      - run: pnpm --filter "@helpwave/*" lint
      - run: pnpm --filter "@helpwave/*" build
